# Name of your site (displayed in the header)
name: Udapi

# Short bio or description (displayed in the header)
description: API and multi-language framework for processing Universal Dependencies

# URL of your avatar or profile pic
avatar: favicon.ico

# Your website URL, used for Sitemap.xml and your RSS feed
url: http://udapi.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
#   # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
#   syntax_highlighter: rouge
#   syntax_highlighter_opts:
#     # Use existing pygments syntax highlighting css
#     css_class: 'highlight'


# Use the following plug-ins
#gems:
#  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
#  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
